### ISSUE TITLE
service2 name: service1-ingress and service1-stripprefix

### ISSUE THREAD

**Issue by mpk166** [iamNoah1/aks-traefik-ingress#2]
First of all thanks for the blog post :)

I have followed your guide and had an issue with loading the services at the end.
After looking into the code and I changed service1-ingress and service1-stripprefix with a 2 and it started to work.

It was a good troubleshooting exercise though.

**Comment by iamNoah1** [comment]
haha, that was on purpose of course to see if people pay attention and try things out ^^. ... Just kidding, nice catch. Thanks. I fixed it.
